version: '3.4'

services:

  php7fpm:
    build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./php7-ini/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - frontend_network

  mysql:
    image: mysql:5.7.21
    container_name: docker-mysql
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
#     - MYSQL_DATABASE=db_admin
#     - MYSQL_USER=admin
#     - MYSQL_PASSWORD=123456
      - VIRTUAL_PORT=3306
      - TERM=xterm
    volumes:
      - ./database/mysql/backup:/backup
      - ./database/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --innodb-buffer-pool-size=20M
    networks:
      - frontend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    container_name: docker-phpmyadmin
    restart: always
    environment:
      - VIRTUAL_PORT=8080
      - PMA_HOST=mysql
#     - PMA_USER=admin
#     - PMA_PASSWORD=123456
      - TERM=xterm
    links:
      - "mysql:mysql"
    ports:
      - "8080:80"
    networks:
      - frontend_network

  nginx:
    image: nginx:1.12.2-alpine
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=80
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./vhosts:/etc/nginx/conf.d/vhosts
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
    networks:
      - frontend_network

networks:
  frontend_network: