version: '2'

services:

  mongo:
    image: mongo:3.4.0
    container_name: docker-mongo
    restart: always
    environment:
      - AUTH=no
      - TERM=xterm
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles
#   command: mongod --smallfiles --auth